Update update-badge.yml
update api and add function to calculate remaining blocks

diff --git a/.github/workflows/update-badge.yml b/.github/workflows/update-badge.yml
--- a/.github/workflows/update-badge.yml
+++ b/.github/workflows/update-badge.yml
@@ -2,7 +2,7 @@ name: Update Expected Block Countdown Badge
 
 on:
   schedule:
-    - cron: "0 * * * *"
+    - cron: "0 * * * *" # Run every hour
   workflow_dispatch:
 
 jobs:
@@ -15,26 +15,33 @@ jobs:
       - name: Fetch Remaining Blocks
         id: fetch-blocks
         run: |
-          RESPONSE=$(curl -s https://namada.valopers.com/blocks/)
+          RESPONSE=$(curl -s -H "Content-Type: application/json" https://api.namada.info/block/last)
 
-          CURRENT_BLOCK=$(echo "$RESPONSE" | grep -oP '(?<=Target Block : #)\d+')
+          CURRENT_BLOCK=$(echo "$RESPONSE" | jq '.height')
+
+          if [[ -z "$CURRENT_BLOCK" ]]; then
+            echo "Error: Unable to fetch the current block height."
+            exit 1
+          fi
 
           REMAINING_BLOCKS=$((894000 - CURRENT_BLOCK))
 
-          echo "Remaining blocks: $REMAINING_BLOCKS"
+          echo "Current Block Height: $CURRENT_BLOCK"
+          echo "Remaining Blocks: $REMAINING_BLOCKS"
 
           echo "blocks=$REMAINING_BLOCKS" >> $GITHUB_OUTPUT
 
       - name: Update README Badge
         run: |
+          # Update the badge in README.md
           sed -i "s|https://img.shields.io/badge/Expected_Update-[0-9]*-blue|https://img.shields.io/badge/Expected_Update-${{ steps.fetch-blocks.outputs.blocks }}-blue|g" README.md
 
       - name: Commit and Push Changes
         run: |
+          # Configure Git user
           git config --global user.name "github-actions"
           git config --global user.email "actions@github.com"
 
           git add README.md
           git commit -m "Updated expected update countdown badge" || echo "No changes to commit"
           git push
-
